name: 'Increment UPM Version'
description: 'Update minor version number of a Unity Package'
inputs:
  package-json:  # id of input
    description: 'path to Unity package.json file'
    required: true
    default: 'package.json'
outputs:
  new-version: # id of output
    description: 'Incremented version number xx.yy.zz'
runs:
  using: 'node16'
  main: 'index.js'
