name: 'Get JSON Value'
description: 'Get a value from a json file'
inputs:
  path:  # id of input
    description: 'path to json file'
    required: true
    default: 'package.json'
  increment:  
    description: 'which number to increment: major|minor|patch|none'
    required: true
    default: 'none'
outputs:
  version: # id of output
    description: 'version'
  major: # id of output
    description: 'major version number'
  minor: # id of output
    description: 'minor version number'
  patch: # id of output
    description: 'patch version number'
runs:
  using: 'node16'
  main: 'index.js'
