name: 'Get JSON Value'
description: 'Get a value from a json file'
inputs:
  path:  # id of input
    description: 'path to json file'
    required: true
    default: 'package.json'
  increment:  
    description: 'which number to increment: major|minor|patch'
    required: true
    default: 'patch'
  github_token:  
    description: 'GitHub access token'
    required: true
    default: ${{ github.token }}
outputs:
  version: # id of output
    description: 'version'
  incremented: # id of output
    description: 'incremented'
runs:
  using: 'node16'
  main: 'index.js'
