name: 'Get JSON Value'
description: 'Get a value from a json file'
inputs:
  path:  # id of input
    description: 'path to json file'
    required: true
    default: 'package.json'
  key:  
    description: 'key to retrieve value for'
    required: true
    default: 'version'
outputs:
  value: # id of output
    description: 'Output Value'
runs:
  using: 'node16'
  main: 'index.js'
